# Generated by Django 4.2.13 on 2026-06-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CARD', 'Tarjeta'), ('BANK_ACCOUNT', 'Cuenta Bancaria'), ('CLABE', 'CLABE'), ('OTHER', 'Otro')], max_length=20)),
                ('alias', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('identifier_encrypted', models.TextField()),
                ('identifier_last4', models.CharField(max_length=4)),
                ('identifier_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'payment_methods',
                'ordering': ['-created_at'],
            },
        ),
    ]
